# Generated by Django 2.2 on 2019-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='text',
        ),
        migrations.AddField(
            model_name='progress',
            name='course',
            field=models.CharField(default='/static/courses/blockchain.html', max_length=255),
        ),
        migrations.AddField(
            model_name='progress',
            name='progress',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
