# Generated by Django 2.2 on 2019-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190414_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='course',
            new_name='course_URL',
        ),
        migrations.AddField(
            model_name='progress',
            name='course_code',
            field=models.CharField(default='BC-101', max_length=255),
        ),
        migrations.AddField(
            model_name='progress',
            name='course_name',
            field=models.CharField(default='Blockchain 101', max_length=255),
        ),
    ]
