# Generated by Django 2.2.4 on 2019-09-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_reached_progress',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
