# Generated by Django 2.2.4 on 2019-09-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_progress_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
